domain: your-name-server-domain (eg) test.example.com .. and so on)
port: tcp, udp open port number(default->53)
aws:
  enable: true or false
  access_key: your-aws-access-key
  secret_access_key: your-aws-secret-access-key
  regions:
    - your-aws-region-1
    - your-aws-region-2
gcp:
  enable: true or false
  project_id: your-gcp-project-id
  zones:
    - your-gcp-zone-1
    - your-gcp-zone-2
  jwt: your-gcp-json-web-token-string
